# Generated by Django 6.0.1 on 2026-01-30 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=30)),
                ('applicant_type', models.CharField(choices=[('CAMPESINO', 'Campesino'), ('ASOCIACION', 'Asociación')], max_length=20)),
                ('request_type', models.CharField(choices=[('CAPACITACION', 'Capacitación'), ('PROYECTO_PRODUCTIVO', 'Proyecto productivo')], max_length=30)),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('REGISTRADA', 'Registrada'), ('EN_REVISION', 'En revisión'), ('EN_AJUSTES', 'En ajustes'), ('VALIDADA', 'Validada'), ('VALIDADA_PARA_ENVIO', 'Validada para envío')], default='BORRADOR', max_length=30)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
