# Generated by Django 6.0.1 on 2026-02-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='external_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
