# Generated by Django 6.0.1 on 2026-02-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='document_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='document_type',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cédula extranjería'), ('NIT', 'NIT')], max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('document_type__isnull', False), ('document_number__isnull', False)), fields=('document_type', 'document_number'), name='uniq_document_type_number'),
        ),
    ]
